name: Build Docker Image with Kaniko

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: self-hosted  # Use the self-hosted runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image with Kaniko
        env:
          KANIKO_IMAGE_NAME: your-image-name:tag
        run: |
          echo "FROM scratch ADD hello / CMD ["/hello"]" > /kaniko/workspace/Dockerfile
          echo "Additional files if needed" > /kaniko/build-context/other-file
          docker run --rm -v /kaniko/build-context:/workspace gcr.io/kaniko-project/executor:latest --context /workspace --dockerfile /workspace/Dockerfile --destination $KANIKO_IMAGE_NAME
