name: Build Docker Image with Kaniko

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: self-hosted  # Use the self-hosted runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image with Kaniko
        env:
          KANIKO_IMAGE_NAME: your-image-name:tag
        run: |
            cp Dockerfile >> /kaniko/workspace/Dockerfile
            cat /kaniko/workspace/Dockerfile
